import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URLDecoder;
import java.net.URLEncoder;
import java.util.TreeSet;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

// TODO: Auto-generated Javadoc
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * The Class FirstResults.
 *
 * @author Rushabh Doshi
 */
public class FirstResults extends javax.swing.JFrame
{

	/** The res. */
	String res[] = new String[5];

	/** The query. */
	String query;

	/**
	 * Instantiates a new first results.
	 */
	public FirstResults()
	{
		this.initComponents();

	}

	/**
	 * Instantiates a new first results.
	 *
	 * @param query
	 *                the query
	 */
	public FirstResults(String query)
	{
		this.initComponents();
		this.loadquery(query);
		this.query = query;
	}

	/**
	 * Loadquery.
	 *
	 * @param query
	 *                the query
	 */
	void loadquery(String query)
	{
		int i = 0;

		String google = "http://www.google.com/search?q=";
		String charset = "UTF-8";
		String userAgent = "ExampleBot 1.0 (+http://example.com/bot)";
		TreeSet<String> results = new TreeSet<String>();

		try
		{
			Elements links = Jsoup.connect(google + URLEncoder.encode(query, charset)).userAgent(userAgent).get().select(".g>.r>a");

			for (Element link : links)
			{
				String title = link.text();
				String url = link.absUrl("href"); // Google
				// returns
				// URLs
				// in
				// format
				// "http://www.google.com/url?q=<url>&sa=U&ei=<someKey>".
				url = URLDecoder.decode(url.substring(url.indexOf('=') + 1, url.indexOf('&')), "UTF-8");

				if (!url.startsWith("http"))
				{
					continue; // Ads/news/etc.
				}

				System.out.println("Title: " + title);
				System.out.println("URL: " + url);
				if (results.size() < 5)
				{
					this.jTable1.getModel().setValueAt(i + 1, i, 0);
					this.jTable1.getModel().setValueAt(url, i, 1);
					if (results.add(url))
					{
						i++;
					}
				}
			}

			res = results.toArray(new String[0]);

		}
		catch (Exception e)
		{
			System.out.println(e.getMessage());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		this.jPanel1 = new javax.swing.JPanel();
		this.jLabel1 = new javax.swing.JLabel();
		this.jSeparator1 = new javax.swing.JSeparator();
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.jTable1 = new javax.swing.JTable();
		this.jLabel2 = new javax.swing.JLabel();
		this.jButton1 = new javax.swing.JButton();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		this.jPanel1.setBackground(new java.awt.Color(0, 153, 153));

		this.jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
		this.jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		this.jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		this.jLabel1.setText("Showing Majority Based Results");

		this.jTable1.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
		this.jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null }, { null, null }, { null, null }, { null, null }, { null, null } },
				new String[] { "Sr No.", "Link" })
		{
			Class[] types = new Class[] { java.lang.Integer.class, java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false };

			@Override
			public Class getColumnClass(int columnIndex)
			{
				return this.types[columnIndex];
			}

			@Override
			public boolean isCellEditable(int rowIndex, int columnIndex)
			{
				return this.canEdit[columnIndex];
			}
		});

		this.jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener()
		{
			@Override
			public void valueChanged(ListSelectionEvent event)
			{
				try
				{
					String resultURI = FirstResults.this.jTable1.getValueAt(FirstResults.this.jTable1.getSelectedRow(), 1).toString();
					System.out.println("Opening " + resultURI);
					final URI uri = new URI(resultURI);
					if (event.getValueIsAdjusting() && Desktop.isDesktopSupported())
					{
						try
						{
							Desktop.getDesktop().browse(uri);
						}
						catch (IOException e)
						{
							JOptionPane.showMessageDialog(FirstResults.this, e.getMessage());
						}
					}

				}
				catch (Exception e)
				{
					JOptionPane.showMessageDialog(FirstResults.this, "Browser Permission Not Available. Run software in administrator mode.");
				}

			}
		});

		this.jScrollPane1.setViewportView(this.jTable1);

		this.jLabel2.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
		this.jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		this.jLabel2.setText("Phase 1 Results : ");

		this.jButton1.setBackground(new java.awt.Color(153, 255, 255));
		this.jButton1.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
		this.jButton1.setText("Continue to Phase II");
		this.jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				// JOptionPane.showMessageDialog(FirstResults.this,
				// "Phase 2 yet to implemented.");
				new SecondResults(FirstResults.this.res, FirstResults.this.query).setVisible(true);

			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(this.jPanel1);
		this.jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(this.jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(this.jSeparator1)
				.addGroup(jPanel1Layout
						.createSequentialGroup()
						.addGroup(jPanel1Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19).addComponent(this.jLabel2))
								.addGroup(jPanel1Layout
										.createSequentialGroup()
										.addGap(134, 134, 134)
										.addComponent(this.jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 481,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
														jPanel1Layout.createSequentialGroup()
														.addGap(0, 28, Short.MAX_VALUE)
														.addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700,
																javax.swing.GroupLayout.PREFERRED_SIZE).addGap(25, 25, 25)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(this.jLabel1)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(this.jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18).addComponent(this.jLabel2).addGap(30, 30, 30)
				.addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE).addComponent(this.jButton1)
				.addGap(45, 45, 45)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
				.addComponent(this.jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
				.addComponent(this.jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)));

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * The main method.
	 *
	 * @param args
	 *                the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay
		 * with the default look and feel. For details see
		 * http://download
		 * .oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(FirstResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(FirstResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(FirstResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(FirstResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			@Override
			public void run()
			{
				new FirstResults().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	/** The j button1. */
	private javax.swing.JButton jButton1;

	/** The j label1. */
	private javax.swing.JLabel jLabel1;

	/** The j label2. */
	private javax.swing.JLabel jLabel2;

	/** The j panel1. */
	private javax.swing.JPanel jPanel1;

	/** The j scroll pane1. */
	private javax.swing.JScrollPane jScrollPane1;

	/** The j separator1. */
	private javax.swing.JSeparator jSeparator1;

	/** The j table1. */
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables
}
